services:
  db:
    platform: linux/amd64
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
    - app_network

  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://myuser:mypassword@host.docker.internal:5432/postgres
    container_name: prisma_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: {}
